import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react'
import Card from '../components/widgets/Card'
import CoursesContext from '../context/CoursesContext'

const Home: NextPage = () => {
	const { coursesList } = useContext(CoursesContext)
	return (
		<>
			<Head>
				<title>Welcome to Namaste Dev</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<main>
				<h1 className="text-center text-2xl mt-4">Featured Courses</h1>
				<div className="courses grid justify-items-center gap-8 px-2 py-8 mx-auto sm:px-4 md:px-6 max-w-none b0:max-w-[368px] b1:max-w-[720px] b2:max-w-[1072px] b3:max-w-[1424px] b4:max-w-[1776px]">
					{coursesList.filter((course) => course.episodeCount > 8).map((course) => (<Card key={course.id} {...course} />))}
				</div>
			</main>
		</>
	)
}

export default Home
